runtime: php81  # language of the app
env: standard
# runtime_config:
    # document_root: public   #folder where index.php is
env_variables:
    GOOGLE_VISION_PROJECT_ID : blue-beard-capital
    APP_ENV: production
    APP_KEY: base64:bTcR1ZwIo9b+5/FP/7qWEReIqMVau8yKX/Y/iOXnO/M=
    APP_DEBUG: true
    APP_LOG_LEVEL: debug
    APP_URL: http://localhost
    DB_CONNECTION: mysql
    DB_HOST: db
    DB_PORT: 3306
    DB_DATABASE: crater
    DB_USERNAME: crater
    DB_PASSWORD: "crater"
    BROADCAST_DRIVER: log
    CACHE_DRIVER: file
    QUEUE_DRIVER: sync
    SESSION_DRIVER: cookie
    SESSION_LIFETIME: 1440
    MAIL_DRIVER: mail
    MAIL_HOST:
    MAIL_PORT:
    MAIL_USERNAME:
    MAIL_PASSWORD:
    MAIL_ENCRYPTION:
    MAIL_FROM_ADDRESS: mehdi@test.com
    MAIL_FROM_NAME: "mehdi test"
    SANCTUM_STATEFUL_DOMAINS: localhost
    SESSION_DOMAIN: localhost
    TRUSTED_PROXIES: "*"
    CRON_JOB_AUTH_TOKEN: ""
